from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import List
import io
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors

router = APIRouter()

class ReportRequest(BaseModel):
    user_name: str
    job_title: str
    predicted_salary: str
    skills: List[str]
    roadmap: List[str]

def create_pdf_report(data: ReportRequest) -> io.BytesIO:
    buffer = io.BytesIO()
    
    # Create the PDF object, using the buffer as its "file."
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    
    # Header
    c.setFont("Helvetica-Bold", 24)
    c.setFillColor(colors.HexColor("#1B2B4B"))
    c.drawString(50, height - 70, "Salary Intelligence Platform")
    
    c.setFont("Helvetica", 14)
    c.setFillColor(colors.gray)
    c.drawString(50, height - 95, "Personalized Career & Salary Report")
    
    c.line(50, height - 110, width - 50, height - 110)
    
    # Profile Info
    c.setFont("Helvetica-Bold", 14)
    c.setFillColor(colors.black)
    c.drawString(50, height - 150, f"Prepared For: {data.user_name}")
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 170, f"Target Role: {data.job_title}")
    
    # Section 1: Salary Prediction
    c.setFont("Helvetica-Bold", 16)
    c.setFillColor(colors.HexColor("#2F80ED"))
    c.drawString(50, height - 220, "1. Salary Benchmark Prediction")
    
    c.setFont("Helvetica", 14)
    c.setFillColor(colors.black)
    c.drawString(70, height - 250, f"Estimated Median Salary: {data.predicted_salary}")
    
    # Section 2: Skill Insights
    c.setFont("Helvetica-Bold", 16)
    c.setFillColor(colors.HexColor("#2F80ED"))
    c.drawString(50, height - 310, "2. High-ROI Skill Recommendations")
    
    c.setFont("Helvetica", 12)
    c.setFillColor(colors.black)
    y_pos = height - 340
    for skill in data.skills:
        c.drawString(70, y_pos, f"• {skill}")
        y_pos -= 20
        
    # Section 3: Career Roadmap
    c.setFont("Helvetica-Bold", 16)
    c.setFillColor(colors.HexColor("#2F80ED"))
    y_pos -= 30
    c.drawString(50, y_pos, "3. Career Progression Roadmap")
    
    c.setFont("Helvetica", 12)
    c.setFillColor(colors.black)
    y_pos -= 30
    for step in data.roadmap:
        c.drawString(70, y_pos, f"→ {step}")
        y_pos -= 25
        
    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.setFillColor(colors.gray)
    c.drawString(50, 50, "Generated by Salary Intelligence Platform AI. Confidential & Proprietary.")
    
    # Finalize PDF
    c.showPage()
    c.save()
    
    buffer.seek(0)
    return buffer

@router.post("/generate-report")
def api_generate_report(payload: ReportRequest):
    pdf_buffer = create_pdf_report(payload)
    return StreamingResponse(
        pdf_buffer, 
        media_type="application/pdf", 
        headers={"Content-Disposition": f"attachment; filename=Salary_Report_{payload.user_name.replace(' ', '_')}.pdf"}
    )
